### PR TITLE
add rank-1 dicodile to basic learn_d_z_multi test

### PR DESCRIPTION
**Pull request by rprimet**

### CODE REVIEW

**Review by tomMoral — APPROVED** [review]
LGTM

**Comment by tomMoral** [comment]
Any idea why the CI is red?

**Comment by rprimet** [comment]
Transient error maybe? It seems OK after a retry.

**Comment by tomMoral** [comment]
Ok this seems to be an random bug on the CI, probably from master.
Merging this one then.

**Pull request merged**
