### PR TITLE
ENH Create docs for multiple release versions

### PR DESCRIPTION
**Pull request by hndgzkn**
Uses `sphinx-multiversion` to create the docs for each release.

### CODE REVIEW

**Comment by agramfort** [comment]
@hndgzkn you need my help to debug? if not can you share a rendered version?

**Comment by hndgzkn** [comment]
> @hndgzkn you need my help to debug? if not can you share a rendered version?

I think it is due to brach/tag settings in `conf.py` file. The error is:

`No matching refs found!`

What I have in local is:

multi

**Comment by agramfort** [comment]
we should have a build of the doc done by the CIs right? it's broken here?

**Comment by hndgzkn** [comment]
> we should have a build of the doc done by the CIs right? it's broken here?

Yes.

**Comment by agramfort** [comment]
you know how to fix?

**Comment by hndgzkn** [comment]
> you know how to fix?

I've set `fetch-depth: 0` in `checkout` github action to fetch all history for all branches and tags. See https://github.com/actions/checkout . It can get the refs now. CI started building the docs. It will take some time, then we can check the result.

**Comment by hndgzkn** [comment]
> it's failing now cause it's taking too much time?

No, it is due to running sphinx-build with MPI. I try to repeat it locally, but I have a problem installing MPI.

**Comment by agramfort** [comment]
I am no MPI wizard sadly :(

**Comment by hndgzkn** [comment]
> I am no MPI wizard sadly :(

`sphinx-multiversion` starts processes using `subprocess`. It causes problem with MPI. 

I found [this issue](https://github.com/open-mpi/ompi/issues/3158), I am trying to understand how I can fix the problem.

**Pull request closed without merging**
